#pragma once

#define WINDOW_WIDTH						1280
#define WINDOW_HEIGHT					800

#define MAIN_MAP_WIDTH					1600.f
#define MAIN_MAP_HEIGHT					1200.f
#define FRAME_WIDTH						750.f
#define FRAME_HEIGHT						750.f


#define CHAR_SPEED						200.f
#define CHAR_FAST_SPEED					300.f
#define CHAR_HIT_RADIUS					5.f
#define ASTEROID_HIT_RADIUS				50.f

#define BULLET_HIT_RADIUS				10.f

#define MAX_BULLET_NUM					1000
#define MAX_SATELLITE_NUM				50
#define MAX_ASTEROID_NUM					30

#define BULLET_SPEED						200.f
#define ACCELBULLET_SPEED				200.f
#define CURVEBULLET_SPEED				200.f

#define ACCELBULLET_ACCEL				200.f
#define CURVEBULLET_ANGULAR_ACCEL		30.f

#define SHOT_BULLET_COST					1
#define SHOT_ACCELBULLET_COST			2
#define SECTOR_SINGLE_COST				3
#define TORNADO_SINGLE_COST				3
#define SETUP_SATELLITE_COST				10
#define SL_SECTORNORMAL_COST				30

#define SHOT_POINT						20.f




#define MAIN_MENU_SCENE_BACKGROUND_SOUND		"Sound/Space_Sprinkles.mp3"
#define MAIN_MENU_SCENE_BACKGROUND_IMAGE		L"Sprite/Background.jpg"
#define MAIN_MENU_SCENE_LOGO					L"Sprite/logo.png"
#define MAIN_MAP_BACKGROUND_IMAGE			L"Sprite/Space-Background.jpg"
#define GAME_FONT							L"Font/¸ð¸®½º-9"

#define FONT_IMAGE					L"Sprite/font.png"
#define FONT_WIDTH					31
#define FONT_HEIGHT					25

enum FontIndex
{
	FONT_MARK_SPACE = 0,
	FONT_MARK_EXCLAMATION = 1,
	FONT_MARK_DOUBLE_QUOTATION = 2,
	FONT_MARK_PERCENT = 5,
	FONT_MARK_SINGLE_QUOTATION = 7,
	FONT_MARK_BRACKET_OPEN = 8,
	FONT_MARK_BRACKET_CLOSE = 9,
	FONT_MARK_PLUS = 11,
	FONT_MARK_COMMA = 12,
	FONT_MARK_HYPHEN = 13,
	FONT_MARK_PEROID = 14,
	FONT_MARK_SLASH = 15,
	FONT_NUM_START = 16,
	FONT_NUM_0 = 16,
	FONT_NUM_1,
	FONT_NUM_2,
	FONT_NUM_3,
	FONT_NUM_4,
	FONT_NUM_5,
	FONT_NUM_6,
	FONT_NUM_7,
	FONT_NUM_8,
	FONT_NUM_9,
	FONT_NUM_END = 25,
	FONT_MARK_CONLON = 26,
	FONT_MARK_SEMI_CONLON = 27,
	FONT_MARK_EQUAL = 29,
	FONT_MARK_QUESTION = 31,
	FONT_ALPHABET_START = 33,
	FONT_ALPHABET_A = 33,
	FONT_ALPHABET_B,
	FONT_ALPHABET_C,
	FONT_ALPHABET_D,
	FONT_ALPHABET_E,
	FONT_ALPHABET_F,
	FONT_ALPHABET_G,
	FONT_ALPHABET_H,
	FONT_ALPHABET_I,
	FONT_ALPHABET_J,
	FONT_ALPHABET_K,
	FONT_ALPHABET_L,
	FONT_ALPHABET_M,
	FONT_ALPHABET_N,
	FONT_ALPHABET_O,
	FONT_ALPHABET_P,
	FONT_ALPHABET_Q,
	FONT_ALPHABET_R,
	FONT_ALPHABET_S,
	FONT_ALPHABET_T,
	FONT_ALPHABET_U,
	FONT_ALPHABET_V,
	FONT_ALPHABET_W,
	FONT_ALPHABET_X,
	FONT_ALPHABET_Y,
	FONT_ALPHABET_Z,
	FONT_ALPHABET_END = 58,
	FONT_MARK_MINUS = 63
};


enum ECharcterStage
{
	FIRST_STAGE_CHAR,
};

enum EBulletType
{
	NORMAL_BULLET,
	ACCEL_BULLET,
	CURVE_BULLET
};

enum ESatelliteType
{
	NORMAL_SATELLITE,
	MOVE_SATELLIE,
	RUSH_SATELLIE
};

enum ESkill
{
	NORMAL,
	SHOT_BULLET,
	SHOT_ACCELBULLET,
	SHOT_SECTOR_NORMAL,
	SHOT_SECTOR_MIX,
	SHOT_TORNADO,
	SETUP_SATELLITE,
	SL_SECTORNORMAL,
};

enum EInputSetUp
{
	NONE,
	UP,
	DOWN,
	LEFT,
	RIGHT,
	LEFT_UP,
	RIGHT_UP,
	LEFT_DOWN,
	RIGHT_DOWN,
	SKILL_KEY_ONE,
	SKILL_KEY_TWO,
	SKILL_KEY_THREE,
	SKILL_KEY_FOUR,
	SKILL_KEY_FIVE,
	SKILL_KEY_SIX,
	UPGRADE_KEY,
	CHANGE_SPEED,
	PAUSE
};

enum EMenuList
{
	MENU_PLAY,
	MENU_TEST,
	MENU_QUIT,
	MENU_NUM,
};


enum ENetworkMode
{
	NET_MENU_FIRST = 0,
	TEST_MODE = 0,
	CLIENT_MODE,
	SERVER_MODE,
	NET_MENU_LAST
};