#pragma once

#define CHARIC_SPEED				200.f
#define CHARIC_FAST_SPEED		300.f

#define MAX_BULLET_NUM			500
#define MAX_ACCELBULLET_NUM		500
#define MAX_CURVEBULLET_NUM		500
#define MAX_SATELLITE_NUM		20

#define BULLET_SPEED				200.f
#define ACCELBULLET_SPEED		100.f
#define CURVEBULLET_SPEED		200.f

#define ACCELBULLET_ACCELERATION	300.f
#define ANGULAR_ACCELERATION	30.f

#define SHOTBULLET_COST			5
#define SHOTACCELBULLET_COST		10
#define SECTOR_SINGLE_COST		3
#define TORNADO_SINGLE_COST		3
#define SETUPSATELLITE_COST		10
#define SL_SECTORNORMAL_COST		10

#define SHOT_POINT				20.f

enum Skill
{
	NORMAL,
	SHOTBULLET,
	SHOTACCELBULLET,
	SHOTSECTORNORMAL,
	SHOTSECTORMIX,
	SHOTTORNADO,
	SETUPSATELLITE,
	SL_SECTORNORMAL,
};

enum InputSetUp
{
	ELSE,
	UP,
	DOWN,
	LEFT,
	RIGHT,
	LEFT_UP,
	RIGHT_UP,
	LEFT_DOWN,
	RIGHT_DOWN,
	SKILL_KEY_ONE,
	SKILL_KEY_TWO,
	SKILL_KEY_THREE,
	SKILL_KEY_FOUR,
	SKILL_KEY_FIVE,
	SKILL_KEY_SIX,
	UPGRADE_KEY,
	CHANGE_SPEED,
	PAUSE
};

enum MENU_LIST
{
	MENU_PLAY,
	MENU_TEST,
	MENU_QUIT,
	MENU_LAST,
};

